title: Exotic Cinema
description: Encounters with Cultural Difference in Contemporary Transnational Cinema
header_text: Exotic Cinema
header_text_color: "#ffffff"
footer_text: Copyright 2022 Daniela Berghahn
header_feature_image: ../uploads/TANNAMainStillDainandWawaonrock.jpg
bannerheight: "35vmax"
gridlayout: true
logo:
favicon: /uploads/favicon.ico
upzoom: true
fixednavbar: true
