title: Exotic Cinema
description: Encounters with Cultural Difference in Contemporary Transnational Cinema
footer_text: Copyright 2023 Daniela Berghahn
header_feature_image: ../uploads/TANNAMainStillDainandWawaonrock.jpg
header_text: Exotic Cinema
header_text_color: "#ffffff"
bannerheight: 35vmax
logo: null
favicon: /uploads/favicon.ico
gridlayout: true
fixednavbar: true
upzoom: true
items:
  - name: Blog
    siteurl: /blog/
